# Generated by Django 2.2.7 on 2019-11-25 06:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this reservation', primary_key=True, serialize=False)),
                ('Reservation start time', models.DateTimeField()),
                ('Reservation end time', models.DateTimeField()),
            ],
        ),
    ]
