# Generated by Django 2.2.7 on 2019-11-25 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoomReservation',
            new_name='RoomReservationModel',
        ),
    ]
